{% set name = "tango-test" %}
{% set version = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/TangoTest/-/releases/{{ version }}/downloads/TangoTest-with-submodules-{{ version }}.tar.gz
  sha256: 71e5f6273212053748901ed1c7174db394e15a18301aef7de68d54f90cc979b9
  patches:
    - find-zeromq.patch  # [win]

build:
  number: 3

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - libtool                 # [unix]
    - pkg-config              # [unix]
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    # TangoTest --help returns 255, so grep the stderr for test
    - TangoTest --help 2>&1 | grep usage         # [unix]
    - TangoTest.exe --help 2>&1 | findstr usage  # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: TangoTest device server
  description: |
    This is the Tango-Controls TangoTest device server.
    A famous TANGO device server developed for testing.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/TangoTest
  doc_url: https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-try-tango.html#play-with-tango-controls
  doc_source_url: https://gitlab.com/tango-controls/TangoTest/tree/main/doc_html

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
